### PR TITLE
Fix various build configs for clean PRs and happy CIs

### PR DESCRIPTION
**Pull request by shipilev**
As synopsis says. The target is to make PRs all green.

Pre-requisites:
- [x] https://github.com/openjdk/leyden/pull/11 to relax jchecks and turn them green
- [x] [SKARA-2353](https://bugs.openjdk.org/browse/SKARA-2353) to show up GHA results here
- [x]  [JDK-8338286](https://bugs.openjdk.org/browse/JDK-8338286) to demote x86-32 jobs to only builds, can be picked with the merge from mainline

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/leyden.git pull/10/head:pull/10` \
`$ git checkout pull/10`

Update a local copy of the PR: \
`$ git checkout pull/10` \
`$ git pull https://git.openjdk.org/leyden.git pull/10/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10`

View PR using the GUI difftool: \
`$ git pr show -t 10`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/leyden/pull/10.diff">https://git.openjdk.org/leyden/pull/10.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
OK, I think _most_ of the tests are passing. There are some Windows failures, but I don't think they are regression from this PR, and they do not block us.

```
compiler/intrinsics/math/MaxMinOptimizeTest

# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (d:\\a\\leyden\\leyden\\src\\hotspot\\share\\code\\relocInfo.cpp:753), pid=772, tid=3384
#  assert(src->section_index_of(target()) == CodeBuffer::SECT_NONE) failed: postcond
#

Current CompileTask:
C2: F10908 C0 Q0 S17 2256    b          java.lang.invoke.MethodHandles$Lookup::resolveOrFail (47 bytes)

Stack: [0x000000dcb5900000,0x000000dcb5a00000]
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0xd7fe41]  os::win32::platform_print_native_stack+0x101  (os_windows_x86.cpp:235)
V  [jvm.dll+0x110b0af]  VMError::report+0x149f  (vmError.cpp:1011)
V  [jvm.dll+0x110d583]  VMError::report_and_die+0x633  (vmError.cpp:1846)
V  [jvm.dll+0x110dc84]  VMError::report_and_die+0x64  (vmError.cpp:1611)
V  [jvm.dll+0x5bc3eb]  report_vm_error+0x5b  (debug.cpp:193)
V  [jvm.dll+0xe2f5a7]  external_word_Relocation::fix_relocation_after_move+0xd7  (relocInfo.cpp:753)
V  [jvm.dll+0x51605f]  CodeBuffer::relocate_code_to+0x3df  (codeBuffer.cpp:808)
V  [jvm.dll+0x512428]  CodeBuffer::copy_code_to+0xd8  (codeBuffer.cpp:747)
V  [jvm.dll+0xd15d5c]  nmethod::nmethod+0x54c  (nmethod.cpp:1551)
V  [jvm.dll+0xd1ce05]  nmethod::new_nmethod+0x405  (nmethod.cpp:1179)
V  [jvm.dll+0x493732]  ciEnv::register_method+0x842  (ciEnv.cpp:1145)
V  [jvm.dll+0xd8dca6]  PhaseOutput::install_code+0x1f6  (output.cpp:3465)
V  [jvm.dll+0xd8d9f2]  PhaseOutput::install+0x182  (output.cpp:3409)
V  [jvm.dll+0x53d6b3]  Compile::Code_Gen+0x3c3  (compile.cpp:3022)
V  [jvm.dll+0x53c05b]  Compile::Compile+0x12bb  (compile.cpp:887)
V  [jvm.dll+0x437c5d]  C2Compiler::compile_method+0x27d  (c2compiler.cpp:175)
V  [jvm.dll+0x55a5a0]  CompileBroker::invoke_compiler_on_method+0x890  (compileBroker.cpp:2613)
V  [jvm.dll+0x557248]  CompileBroker::compiler_thread_loop+0x488  (compileBroker.cpp:2257)
V  [jvm.dll+0x8a6046]  JavaThread::thread_main_inner+0x266  (javaThread.cpp:762)
V  [jvm.dll+0x1063758]  Thread::call_run+0x1c8  (thread.cpp:241)
V  [jvm.dll+0xd7e486]  thread_native_entry+0xd6  (os_windows.cpp:553)
C  [ucrtbase.dll+0x2268a]  (no source info available)
C  [KERNEL32.DLL+0x17ac4]  (no source info available)
C  [ntdll.dll+0x5a8c1]  (no source info available)
```

**Comment by shipilev** [comment]
Otherwise, we can review and try to integrate this with bots. Please take a look and approve this PR :)

**Comment by shipilev** [comment]
Anyone? @iklam? :)

**Comment by iklam** [comment]
Looks good to me in general. Can you comment why the changes are needed in deoptimization.cpp?

**Comment by shipilev** [comment]
> Looks good to me in general. Can you comment why the changes are needed in deoptimization.cpp?

Those are mostly moving the real counter code under `COMPILER2_OR_JVMCI` macro, leaving the empty stubs for C1-only builds. That's how current code in mainline is structured. Otherwise, IIRC, that some flags are only defined for C2, and Minimal builds start to fail? I can check again, but I think it makes sense on its own.

**Comment by iklam** [comment]
> > Looks good to me in general. Can you comment why the changes are needed in deoptimization.cpp?
> 
> Those are mostly moving the real counter code under `COMPILER2_OR_JVMCI` macro, leaving the empty stubs for C1-only builds. That's how current code in mainline is structured. Otherwise, IIRC, that some flags are only defined for C2, and Minimal builds start to fail? I can check again, but I think it makes sense on its own.

Thanks for the explanation. I've pushed your changes into premain: https://github.com/openjdk/leyden/commit/b96c511323aea6ffb2fc972817c779b4bacaf9fa

**Comment by shipilev** [comment]
> Thanks for the explanation. I've pushed your changes into premain: [b96c511](https://github.com/openjdk/leyden/commit/b96c511323aea6ffb2fc972817c779b4bacaf9fa)

Dang. I wanted to try and integrate this with bots! Oh well, next time.

**Pull request closed without merging**
