### PR TITLE
Enable 1-step workflow with Shenandoah GC

### PR DESCRIPTION
**Pull request by shipilev**
WIP, includes upstream [JDK-8293650](https://bugs.openjdk.org/browse/JDK-8293650).

I checked this works well:

```
#!/bin/bash
make images
J=build/macosx-aarch64-server-fastdebug/images/jdk/bin/java
rm -fv JavacBenchApp.cds*
$J -XX:+UseShenandoahGC -XX:CacheDataStore=JavacBenchApp.cds -cp JavacBenchApp.jar JavacBenchApp 50
$J -XX:+UseShenandoahGC -XX:CacheDataStore=JavacBenchApp.cds -cp JavacBenchApp.jar JavacBenchApp 50
```

I'll look around what other tests I need to run.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Reviewers
 * [Ioi Lam](https://openjdk.org/census#iklam) (@iklam - Committer) ⚠️ Review applies to [f578d65d](https://git.openjdk.org/leyden/pull/8/files/f578d65dd37705caf7aaa1bfeb1aea6ffd5fb44b)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/leyden.git pull/8/head:pull/8` \
`$ git checkout pull/8`

Update a local copy of the PR: \
`$ git checkout pull/8` \
`$ git pull https://git.openjdk.org/leyden.git pull/8/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8`

View PR using the GUI difftool: \
`$ git pr show -t 8`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/leyden/pull/8.diff">https://git.openjdk.org/leyden/pull/8.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/leyden/pull/8#issuecomment-2330209086)

### CODE REVIEW

**Review by iklam — APPROVED** [review]
LGTM

**Comment by shipilev** [comment]
Now waiting for https://github.com/openjdk/jdk/pull/21152 to arrive, so that we don't have a merge problem later.

**Comment by shipilev** [comment]
Thanks for the merge, @iklam! I think we are ready to integrate this.

/integrate

**Pull request closed without merging**
